apiVersion: v1
kind: Service
metadata:
  name: kurt-deployment
spec:
  type: NodePort
  selector:
    app: nginx
    release: nginx
    spec:
      containers:
        image: nginx
        ports:
          -containerPort: 80
